import {expect, test} from "bun:test";
import {countDistance, expand} from "./observatory";
import * as console from "console";
import {readFileSync} from "fs";

test('Expand. No effect.', () => {
    const input = `#.\n.#`.trim();
    const output = `#.\n.#`.trim();
    expect(expand(input)).toBe(output);
})

test('Expand in vertical.', () => {
    const input = `#.\n..\n.#`;
    const output = `#.\n..\n..\n.#`;
    expect(expand(input)).toBe(output);
})

test('Expand in horizontal.', () => {
    const input = `#..\n..#`;
    const output = `#...\n...#`;
    expect(expand(input)).toBe(output);
})

test('Expand. Sample 1.', () => {
    const input = `
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
    `.trim();
    const output = `
....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......
    `.trim();
    expect(expand(input)).toBe(output);
})


test('Count distance. No expansion.', () => {
    const input = `#.\n.#`.trim();
    expect(countDistance(input)).toBe(2);
})

test('Count distance. Expansion in vertical', () => {
    const input = `#.\n..\n..\n.#`;
    expect(countDistance(input)).toBe(4);
})

test('Count distance. Expansion in horizontal.', () => {
    const input = `#...\n...#`;
    expect(countDistance(input)).toBe(4);
})

test('Count distance. Sample 1.', () => {
    const input = `
....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#....... 
    `.trim();
    expect(countDistance(input)).toBe(374);
})

test('Personal. Part 1', () => {
    const input = readFileSync('./input-personal-part-1.txt').toString();
    expect(countDistance(expand(input))).toBe(-1);
})
