import {expect, test} from "bun:test";
import {expand} from "./observatory";

test('Expand. No effect.', () => {
    const input = `#.\n.#`.trim();
    const output = `#.\n.#`.trim();
    expect(expand(input)).toBe(output);
})

test('Expand in vertical.', () => {
    const input = `#.\n..\n.#`;
    const output = `#.\n..\n..\n.#`;
    expect(expand(input)).toBe(output);
})

test('Expand in horizontal.', () => {
    const input = `#..\n..#`;
    const output = `#...\n...#`;
    expect(expand(input)).toBe(output);
})

test('Expand. Sample 1.', () => {
    const input = `
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....    
    `.trim();
    const output = `
....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#....... 
    `.trim();
    expect(expand(input)).toBe(output);
})